name: fonoapi_dart
description: A dart client for FonoAPI.
version: 0.1.0
author: ThinkDigitalSoftware <jwhite@thinkdigital.software>
repository: https://www.github.com/thinkdigitalsoftware/fonoapi-dart
homepage: https://www.github.com/thinkdigitalsoftware/fonoapi-dart


environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.2
